name: helloworldft
description: "A new Flutter project for MAD"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.2 <4.0.0'
dependencies:
  fluttertoast: ^8.0.8
  shared_preferences: ^2.2.2
  flutter:
    sdk: flutter
  geolocator: ^11.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  path_provider: ^2.0.9
  sqflite: ^2.0.0+4
  csv: ^6.0.0
  intl: ^0.19.0
  logger: ^2.2.0
  cupertino_icons: ^1.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
